image: docker:latest
services:
  - name: docker:dind
    alias: docker
stages:
  - "Build images"
  - "Test acceptation"

Build images:
  # Use the official docker image.
  stage: Build images
  script:
    - docker build -t alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts:
    paths:
      - "alpinehelloworld.tar"

Test acceptation:
  # Use the official docker image.
  stage: Test acceptation
  script:
    - docker load < alpinehelloworld.tar
    - docker run -d -p 80:5000 -e PORT=5000  --name webapp alpinehelloworld
    - sleep 10
    - apk --no-cache add curl
    - curl http://docker | grep -q "Hello world!"
    - echo "williams tu es un chef ! c'est propre !"
